version: '3'

services:

    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./application:/application
            - ./docker/nginx/crypto.conf:/etc/nginx/conf.d/default.conf
            #- ./docker/nginx/ssl/crypto.home.crt:/etc/nginx/conf.d/crypto.home.crt
            #- ./docker/nginx/ssl/crypto.home.key:/etc/nginx/conf.d/crypto.home.key
        links:
            - backend
    backend:
        container_name: "crypto-backend"
        image: backend
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./application:/application
        links:
            - postgres

    postgres:
        restart: always
        build: docker/postgres
        hostname: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
