version: '3'

services:

    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./application:/application
            - ./docker/nginx/delivery.conf:/etc/nginx/conf.d/default.conf
            #- ./docker/nginx/ssl/delivery.home.crt:/etc/nginx/conf.d/crypto.home.crt
            #- ./docker/nginx/ssl/delivery.home.key:/etc/nginx/conf.d/crypto.home.key
        links:
            - backend
    backend:
        container_name: "delivery-backend"
        image: backend
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./application:/application


